
site_name: Portal Tech – EY + BB

theme:
  name: material
  language: pt
  palette:
    scheme: slate
    primary: black
    accent: yellow
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight

extra_css:
  - assets/stylesheets/ey-tech.css

nav:
  - Home: index.md
  - Portal:
      - Visão Geral: portal/index.md
      - Governança: portal/governanca.md
      - Sobre: portal/sobre.md
  - Comunidades:
      - Engenharia de Software: comunidades/engenharia/index.md
      - Dados & Analytics: comunidades/dados/index.md
      - Cloud & DevOps: comunidades/cloud/index.md
      - Segurança: comunidades/seguranca/index.md
