site_name: Portal Tech – EY + BB
site_url: https://rodrigo-ramos-ey.github.io/wiki-ey-bb/

theme:
  name: material
  language: pt
  palette:
    scheme: slate
    primary: black
    accent: yellow
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - search.suggest
    - search.highlight

extra_css:
  - assets/stylesheets/ey-tech.css

nav:
  - Home: index.md

  - Portal:
      - Visão Geral: portal/index.md
      - Sobre o Portal: portal/sobre/index.md
      - Governança: portal/governanca/index.md
      - Comunidades: portal/comunidades/index.md

  - Comunidades:
      - Engenharia de Software: comunidades/comunidades/engenharia/index.md
      - Dados & Analytics: comunidades/comunidades/dados/index.md
      - Cloud & DevOps: comunidades/comunidades/cloud/index.md
      - Segurança: comunidades/comunidades/seguranca/index.md
